### ISSUE TITLE
Make button texts customizable

### ISSUE THREAD

**Issue by derUli** [Newms34/bulmabox#1]
Actually you have hardcoded "OK" and "Cancel".
In Bootbox it's possible to customize that button text to enable developers to localize their modal dialogs.

**Comment by Newms34** [comment]
Done! Hopefully I've not broken anything. Check the readme for more details/to be further confused at my lack of ability to explain, but basically passing an`options` object will now allow you to determine the color as well as the language/text of the OK/Cancel buttons.
